name: Run changie from PR comment

permissions:
  contents: write
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  # This job only runs for pull request comments
  pr-changie-work:
    name: PR comment
    if: "${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/changie')}}"
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: event-bus # ${{ github.event.pull_request.headRefName }}

    - name: Add env vars
      run: |
        echo COMMAND=$(echo "${{ github.event.comment.body }}" | cut -c10-) >> $GITHUB_ENV
        cat $GITHUB_ENV

    - name: Run changie
      uses: miniscruff/changie-action@v2
      with:
        args: ${{ env.COMMAND }}

    - name: Update PR
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Ran changie action from command"
        git push

